# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'groundstation.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import bgimgw
class Ui_GroundStation(object):
    def setupUi(self, GroundStation):
        GroundStation.setObjectName("GroundStation")
        GroundStation.resize(1117, 791)
        GroundStation.setMaximumSize(QtCore.QSize(1117, 791))
        GroundStation.setStyleSheet("background-image: url(:/img/bgimg.png);")
        self.centralwidget = QtWidgets.QWidget(GroundStation)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 130, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(11, 12, 16);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 170, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(11, 12, 16);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(300, 210, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(11, 12, 16);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(300, 250, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(11, 12, 16);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(300, 290, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(11, 12, 16);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(300, 330, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(11, 12, 16);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(300, 370, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(11, 12, 16);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(300, 410, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(11, 12, 16);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(300, 450, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(11, 12, 16);")
        self.label_9.setObjectName("label_9")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 480, 211, 35))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(69, 162, 158);")
        self.pushButton.setObjectName("pushButton")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(290, 60, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(11, 12, 16);\n"
"color: rgb(102, 252, 241);")
        self.label_10.setObjectName("label_10")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(310, 520, 211, 35))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(69, 162, 158);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(10, 540, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background-color: rgb(11, 12, 16);\n"
"color: rgb(102, 252, 241);")
        self.label_21.setObjectName("label_21")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(850, 60, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("background-color: rgb(11, 12, 16);\n"
"color: rgb(102, 252, 241);")
        self.label_28.setObjectName("label_28")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(870, 420, 211, 35))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(69, 162, 158);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(870, 370, 211, 35))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(69, 162, 158);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(870, 470, 211, 35))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(69, 162, 158);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(870, 520, 211, 35))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(69, 162, 158);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(10, 60, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("background-color: rgb(11, 12, 16);\n"
"color: rgb(102, 252, 241);\n"
"")
        self.label_29.setObjectName("label_29")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(570, 60, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background-color: rgb(11, 12, 16);\n"
"color: rgb(102, 252, 241);")
        self.label_20.setObjectName("label_20")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(870, 250, 211, 35))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(69, 162, 158);")
        self.pushButton_18.setObjectName("pushButton_18")
        self.listView_5 = QtWidgets.QListView(self.centralwidget)
        self.listView_5.setGeometry(QtCore.QRect(850, 110, 256, 241))
        self.listView_5.setStyleSheet("background-color: rgb(11, 12, 16);")
        self.listView_5.setObjectName("listView_5")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(870, 300, 211, 35))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(69, 162, 158);")
        self.pushButton_19.setObjectName("pushButton_19")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(20, 10, 1071, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("background-color: rgb(11, 12, 16);\n"
"color: rgb(102, 252, 241);")
        self.label_30.setObjectName("label_30")
        self.message = QtWidgets.QTextEdit(self.centralwidget)
        self.message.setGeometry(QtCore.QRect(10, 580, 1101, 151))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.message.setFont(font)
        self.message.setStyleSheet("color: rgb(102, 252, 241);")
        self.message.setObjectName("message")
        self.lat1 = QtWidgets.QTextEdit(self.centralwidget)
        self.lat1.setGeometry(QtCore.QRect(410, 120, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.lat1.setFont(font)
        self.lat1.setStyleSheet("color: rgb(102, 252, 241);")
        self.lat1.setObjectName("lat1")
        self.long1 = QtWidgets.QTextEdit(self.centralwidget)
        self.long1.setGeometry(QtCore.QRect(410, 160, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.long1.setFont(font)
        self.long1.setStyleSheet("color: rgb(102, 252, 241);")
        self.long1.setObjectName("long1")
        self.yawd1 = QtWidgets.QTextEdit(self.centralwidget)
        self.yawd1.setGeometry(QtCore.QRect(410, 240, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.yawd1.setFont(font)
        self.yawd1.setStyleSheet("color: rgb(102, 252, 241);")
        self.yawd1.setObjectName("yawd1")
        self.alt1 = QtWidgets.QTextEdit(self.centralwidget)
        self.alt1.setGeometry(QtCore.QRect(410, 200, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.alt1.setFont(font)
        self.alt1.setStyleSheet("color: rgb(102, 252, 241);")
        self.alt1.setObjectName("alt1")
        self.yawc1 = QtWidgets.QTextEdit(self.centralwidget)
        self.yawc1.setGeometry(QtCore.QRect(410, 320, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.yawc1.setFont(font)
        self.yawc1.setStyleSheet("color: rgb(102, 252, 241);")
        self.yawc1.setObjectName("yawc1")
        self.pitchd1 = QtWidgets.QTextEdit(self.centralwidget)
        self.pitchd1.setGeometry(QtCore.QRect(410, 280, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.pitchd1.setFont(font)
        self.pitchd1.setStyleSheet("color: rgb(102, 252, 241);")
        self.pitchd1.setObjectName("pitchd1")
        self.pitcht1 = QtWidgets.QTextEdit(self.centralwidget)
        self.pitcht1.setGeometry(QtCore.QRect(410, 440, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.pitcht1.setFont(font)
        self.pitcht1.setStyleSheet("color: rgb(102, 252, 241);")
        self.pitcht1.setObjectName("pitcht1")
        self.pitchc1 = QtWidgets.QTextEdit(self.centralwidget)
        self.pitchc1.setGeometry(QtCore.QRect(410, 360, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.pitchc1.setFont(font)
        self.pitchc1.setStyleSheet("color: rgb(102, 252, 241);")
        self.pitchc1.setObjectName("pitchc1")
        self.yawt1 = QtWidgets.QTextEdit(self.centralwidget)
        self.yawt1.setGeometry(QtCore.QRect(410, 400, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.yawt1.setFont(font)
        self.yawt1.setStyleSheet("color: rgb(102, 252, 241);")
        self.yawt1.setObjectName("yawt1")
        self.listView_3 = QtWidgets.QListView(self.centralwidget)
        self.listView_3.setGeometry(QtCore.QRect(290, 110, 256, 461))
        self.listView_3.setStyleSheet("background-color: rgb(11, 12, 16);")
        self.listView_3.setObjectName("listView_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(590, 520, 211, 35))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(69, 162, 158);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.alt2 = QtWidgets.QTextEdit(self.centralwidget)
        self.alt2.setGeometry(QtCore.QRect(690, 200, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.alt2.setFont(font)
        self.alt2.setStyleSheet("color: rgb(102, 252, 241);")
        self.alt2.setObjectName("alt2")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(580, 450, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(11, 12, 16);")
        self.label_11.setObjectName("label_11")
        self.long2 = QtWidgets.QTextEdit(self.centralwidget)
        self.long2.setGeometry(QtCore.QRect(690, 160, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.long2.setFont(font)
        self.long2.setStyleSheet("color: rgb(102, 252, 241);")
        self.long2.setObjectName("long2")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(580, 250, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(11, 12, 16);")
        self.label_12.setObjectName("label_12")
        self.pitchd2 = QtWidgets.QTextEdit(self.centralwidget)
        self.pitchd2.setGeometry(QtCore.QRect(690, 280, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.pitchd2.setFont(font)
        self.pitchd2.setStyleSheet("color: rgb(102, 252, 241);")
        self.pitchd2.setObjectName("pitchd2")
        self.pitchc2 = QtWidgets.QTextEdit(self.centralwidget)
        self.pitchc2.setGeometry(QtCore.QRect(690, 360, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.pitchc2.setFont(font)
        self.pitchc2.setStyleSheet("color: rgb(102, 252, 241);")
        self.pitchc2.setObjectName("pitchc2")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(580, 170, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(11, 12, 16);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(580, 330, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(11, 12, 16);")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(580, 130, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(11, 12, 16);")
        self.label_15.setObjectName("label_15")
        self.yawd2 = QtWidgets.QTextEdit(self.centralwidget)
        self.yawd2.setGeometry(QtCore.QRect(690, 240, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.yawd2.setFont(font)
        self.yawd2.setStyleSheet("color: rgb(102, 252, 241);")
        self.yawd2.setObjectName("yawd2")
        self.listView_6 = QtWidgets.QListView(self.centralwidget)
        self.listView_6.setGeometry(QtCore.QRect(570, 110, 256, 461))
        self.listView_6.setStyleSheet("background-color: rgb(11, 12, 16);")
        self.listView_6.setObjectName("listView_6")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(590, 480, 211, 35))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(69, 162, 158);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(580, 290, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(11, 12, 16);")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(580, 410, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(11, 12, 16);")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(580, 370, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(11, 12, 16);")
        self.label_18.setObjectName("label_18")
        self.lat2 = QtWidgets.QTextEdit(self.centralwidget)
        self.lat2.setGeometry(QtCore.QRect(690, 120, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.lat2.setFont(font)
        self.lat2.setStyleSheet("color: rgb(102, 252, 241);")
        self.lat2.setObjectName("lat2")
        self.yawt2 = QtWidgets.QTextEdit(self.centralwidget)
        self.yawt2.setGeometry(QtCore.QRect(690, 400, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.yawt2.setFont(font)
        self.yawt2.setStyleSheet("color: rgb(102, 252, 241);")
        self.yawt2.setObjectName("yawt2")
        self.yawc2 = QtWidgets.QTextEdit(self.centralwidget)
        self.yawc2.setGeometry(QtCore.QRect(690, 320, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.yawc2.setFont(font)
        self.yawc2.setStyleSheet("color: rgb(102, 252, 241);")
        self.yawc2.setObjectName("yawc2")
        self.pitcht2 = QtWidgets.QTextEdit(self.centralwidget)
        self.pitcht2.setGeometry(QtCore.QRect(690, 440, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.pitcht2.setFont(font)
        self.pitcht2.setStyleSheet("color: rgb(102, 252, 241);")
        self.pitcht2.setObjectName("pitcht2")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(580, 210, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(11, 12, 16);")
        self.label_19.setObjectName("label_19")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(870, 170, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(11, 12, 16);")
        self.label_22.setObjectName("label_22")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(870, 130, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(11, 12, 16);")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(870, 210, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(11, 12, 16);")
        self.label_25.setObjectName("label_25")
        self.tlong = QtWidgets.QTextEdit(self.centralwidget)
        self.tlong.setGeometry(QtCore.QRect(980, 160, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.tlong.setFont(font)
        self.tlong.setStyleSheet("color: rgb(102, 252, 241);")
        self.tlong.setObjectName("tlong")
        self.talt = QtWidgets.QTextEdit(self.centralwidget)
        self.talt.setGeometry(QtCore.QRect(980, 200, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.talt.setFont(font)
        self.talt.setStyleSheet("color: rgb(102, 252, 241);")
        self.talt.setObjectName("talt")
        self.tlat = QtWidgets.QTextEdit(self.centralwidget)
        self.tlat.setGeometry(QtCore.QRect(980, 120, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.tlat.setFont(font)
        self.tlat.setStyleSheet("color: rgb(102, 252, 241);")
        self.tlat.setObjectName("tlat")
        self.listView_7 = QtWidgets.QListView(self.centralwidget)
        self.listView_7.setGeometry(QtCore.QRect(10, 110, 256, 291))
        self.listView_7.setStyleSheet("background-color: rgb(11, 12, 16);")
        self.listView_7.setObjectName("listView_7")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(30, 130, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(11, 12, 16);")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(30, 210, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(11, 12, 16);")
        self.label_27.setObjectName("label_27")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(30, 250, 211, 35))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(69, 162, 158);")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(30, 300, 211, 35))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(69, 162, 158);")
        self.pushButton_21.setObjectName("pushButton_21")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(30, 170, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(11, 12, 16);")
        self.label_23.setObjectName("label_23")
        self.glat = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.glat.setGeometry(QtCore.QRect(140, 120, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.glat.setFont(font)
        self.glat.setStyleSheet("color: rgb(102, 252, 241);")
        self.glat.setObjectName("glat")
        self.glong = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.glong.setGeometry(QtCore.QRect(140, 160, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.glong.setFont(font)
        self.glong.setStyleSheet("color: rgb(102, 252, 241);")
        self.glong.setObjectName("glong")
        self.galt = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.galt.setGeometry(QtCore.QRect(140, 200, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.galt.setFont(font)
        self.galt.setStyleSheet("color: rgb(102, 252, 241);")
        self.galt.setObjectName("galt")
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setGeometry(QtCore.QRect(30, 350, 211, 35))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(69, 162, 158);")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(30, 420, 211, 35))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setStyleSheet("color: rgb(102, 252, 241);\n"
"background-color: rgb(69, 162, 158);")
        self.pushButton_23.setObjectName("pushButton_23")
        self.listView_6.raise_()
        self.listView_3.raise_()
        self.listView_5.raise_()
        self.pushButton.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.pushButton_4.raise_()
        self.label_21.raise_()
        self.label_28.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.pushButton_9.raise_()
        self.pushButton_10.raise_()
        self.label_29.raise_()
        self.label_20.raise_()
        self.pushButton_18.raise_()
        self.pushButton_19.raise_()
        self.label_30.raise_()
        self.message.raise_()
        self.lat1.raise_()
        self.long1.raise_()
        self.yawd1.raise_()
        self.alt1.raise_()
        self.yawc1.raise_()
        self.pitchd1.raise_()
        self.pitcht1.raise_()
        self.pitchc1.raise_()
        self.yawt1.raise_()
        self.pushButton_5.raise_()
        self.alt2.raise_()
        self.label_11.raise_()
        self.long2.raise_()
        self.label_12.raise_()
        self.pitchd2.raise_()
        self.pitchc2.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.yawd2.raise_()
        self.pushButton_2.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.lat2.raise_()
        self.yawt2.raise_()
        self.yawc2.raise_()
        self.pitcht2.raise_()
        self.label_19.raise_()
        self.label_22.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.tlong.raise_()
        self.talt.raise_()
        self.tlat.raise_()
        self.listView_7.raise_()
        self.label_26.raise_()
        self.label_27.raise_()
        self.pushButton_20.raise_()
        self.pushButton_21.raise_()
        self.label_23.raise_()
        self.glat.raise_()
        self.glong.raise_()
        self.galt.raise_()
        self.pushButton_22.raise_()
        self.pushButton_23.raise_()
        GroundStation.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GroundStation)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1117, 26))
        self.menubar.setObjectName("menubar")
        GroundStation.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GroundStation)
        self.statusbar.setObjectName("statusbar")
        GroundStation.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(GroundStation)
        self.actionSave.setObjectName("actionSave")
        self.actionClose = QtWidgets.QAction(GroundStation)
        self.actionClose.setObjectName("actionClose")

        self.retranslateUi(GroundStation)
        QtCore.QMetaObject.connectSlotsByName(GroundStation)

    def retranslateUi(self, GroundStation):
        _translate = QtCore.QCoreApplication.translate
        GroundStation.setWindowTitle(_translate("GroundStation", "Ground Station"))
        self.label.setText(_translate("GroundStation", "Latitude"))
        self.label_2.setText(_translate("GroundStation", "Longitude"))
        self.label_3.setText(_translate("GroundStation", "Altitude"))
        self.label_4.setText(_translate("GroundStation", "Yaw - D"))
        self.label_5.setText(_translate("GroundStation", "Pitch - D"))
        self.label_6.setText(_translate("GroundStation", "Yaw - C"))
        self.label_7.setText(_translate("GroundStation", "Pitch - C"))
        self.label_8.setText(_translate("GroundStation", "Yaw - T"))
        self.label_9.setText(_translate("GroundStation", "Pitch - T"))
        self.pushButton.setText(_translate("GroundStation", "Connect DRONE - 1"))
        self.label_10.setText(_translate("GroundStation", "DRONE - 1"))
        self.pushButton_4.setText(_translate("GroundStation", "Open MissionPlanner"))
        self.label_21.setText(_translate("GroundStation", "CONSOLE WINDOW"))
        self.label_28.setText(_translate("GroundStation", "TARGET LOCATION"))
        self.pushButton_7.setText(_translate("GroundStation", "FPV of DRONE - 1"))
        self.pushButton_8.setText(_translate("GroundStation", "Store Data"))
        self.pushButton_9.setText(_translate("GroundStation", "FPV of DRONE - 2"))
        self.pushButton_10.setText(_translate("GroundStation", "Close"))
        self.label_29.setText(_translate("GroundStation", "GROUND STATION"))
        self.label_20.setText(_translate("GroundStation", "DRONE - 2"))
        self.pushButton_18.setText(_translate("GroundStation", "Triangulate"))
        self.pushButton_19.setText(_translate("GroundStation", "Visiual Display"))
        self.label_30.setText(_translate("GroundStation", "3D - TRACKING AND GEO - LOCALIZATION OF TARGET USING UNMANNED AERIAL VEHICLE"))
        self.pushButton_5.setText(_translate("GroundStation", "Open MissionPlanner"))
        self.label_11.setText(_translate("GroundStation", "Pitch - T"))
        self.label_12.setText(_translate("GroundStation", "Yaw - D"))
        self.label_13.setText(_translate("GroundStation", "Longitude"))
        self.label_14.setText(_translate("GroundStation", "Yaw - C"))
        self.label_15.setText(_translate("GroundStation", "Latitude"))
        self.pushButton_2.setText(_translate("GroundStation", "Connect DRONE - 2"))
        self.label_16.setText(_translate("GroundStation", "Pitch - D"))
        self.label_17.setText(_translate("GroundStation", "Yaw - T"))
        self.label_18.setText(_translate("GroundStation", "Pitch - C"))
        self.label_19.setText(_translate("GroundStation", "Altitude"))
        self.label_22.setText(_translate("GroundStation", "Longitude"))
        self.label_24.setText(_translate("GroundStation", "Latitude"))
        self.label_25.setText(_translate("GroundStation", "Altitude"))
        self.label_26.setText(_translate("GroundStation", "Latitude"))
        self.label_27.setText(_translate("GroundStation", "Altitude"))
        self.pushButton_20.setText(_translate("GroundStation", "Submit"))
        self.pushButton_21.setText(_translate("GroundStation", "Post Processing"))
        self.label_23.setText(_translate("GroundStation", "Longitude"))
        self.pushButton_22.setText(_translate("GroundStation", "Real Time Processing"))
        self.pushButton_23.setText(_translate("GroundStation", "Start Server"))
        self.actionSave.setText(_translate("GroundStation", "Save"))
        self.actionClose.setText(_translate("GroundStation", "Close"))


